# Generated by Django 4.2.2 on 2023-06-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0003_remove_userprofile_created_by_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.FileField(upload_to='media/uploads/'),
        ),
    ]
